server:
  port: ${APP_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: DEBUG