server:
#  ssl:
#    key-store: ${BACKEND_APP_SSL_KEYSTORE_PATH}
#    key-store-password: ${BACKEND_APP_SSL_KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: ${BACKEND_APP_SSL_KEYSTORE_ALIAS}
#    enabled: true
port: ${BACKEND_APP_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${BACKEND_OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${BACKEND_OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "${BACKEND_OAUTH2_GOOGLE_AUTHORIZED_REDIRECT_URI}/{registrationId}"
            scope:
              - email
              - profile

logging:
  level:
    root: info
    org.springframework: debug
    org.hibernate: debug
    org.springframework.security: trace